export const day1 = {
  en: {
    title: 'Benefits of Quitting',
    saying: 'Every cigarette not smoked is a win, not a loss.',
    summary: 'Quitting smoking has immediate and long-term benefits, from more energy and money to better health and a longer life.',
    sections: [
      { icon: 'EnergyIcon', title: 'More Energy', content: 'Smoking reduces oxygen in your blood, making your heart and lungs work harder. When you quit, your body can transport oxygen better, and you’ll notice activities like climbing stairs become easier within days.' },
      { icon: 'LungsIcon', title: 'More Air – Literally', content: 'After about 24 hours, your body stops taking in carbon monoxide and begins a major cleanup in your lungs. You might cough up more mucus temporarily, which is a good sign of recovery.' },
      { icon: 'MoneyIcon', title: 'More Money', content: 'If you smoke one pack a day at €8, you save approximately €240 per month, €1,440 in six months, and €2,880 in a year. Calculate your exact savings!' },
      { icon: 'TimeIcon', title: 'More Time', content: 'Smoking takes up a lot of time. Quitting gives you extra time for things you find important or enjoyable.' },
      { icon: 'SleepIcon', title: 'Better Sleep', content: 'Nicotine is a stimulant that disrupts sleep. After initial withdrawal, ex-smokers generally sleep better than smokers.' },
      { icon: 'FocusIcon', title: 'Less Distraction', content: 'As a smoker, you often think about when you can smoke. After a few weeks of quitting, you’ll notice better concentration.' },
      { icon: 'DecisionIcon', title: 'Better Choices', content: 'Successfully quitting smoking gives you a sense of control, making it easier to make other healthy choices.' },
      { icon: 'HealthIcon', title: 'Better Physical Health', content: 'After 1 year, the risk of cardiovascular disease is halved. After 10 years, the risk of lung cancer is halved. Non-smokers live about 10 years longer on average.' },
      { icon: 'ImmuneSystemIcon', title: 'Better Resistance', content: 'Quitting smoking improves your immune system, making you less susceptible to infections.' },
      { icon: 'MoodIcon', title: 'Better Mood', content: 'While many think smoking reduces stress, it often increases it in the long run. After quitting, anxiety, stress, and depressive symptoms often decrease.' },
    ],
    readMore: "Find more facts and figures about smoking and quitting from reliable sources like the Trimbos Institute and RIVM.",
    assignment: 'Write in your journal in the app: “Why do I want to quit/reduce?” Make a list of at least 5 benefits that are most important to you personally. Today, for every cigarette, take a photo in the app and note: where was I? with whom? how did I feel?',
    quiz: [],
  },
  nl: {
    title: 'Voordelen van stoppen',
    saying: 'Elke niet-gerookte sigaret is een winst, geen verlies.',
    summary: 'Stoppen met roken heeft onmiddellijke en langdurige voordelen, van meer energie en geld tot een betere gezondheid en een langer leven.',
    sections: [
      { icon: 'EnergyIcon', title: 'Meer energie', content: 'Roken zorgt ervoor dat er minder zuurstof in je bloed zit. Je hart en longen moeten harder werken. Stop je, dan kan je lichaam de zuurstof beter vervoeren en merk je vaak al binnen een paar dagen dat traplopen makkelijker gaat.' },
      { icon: 'LungsIcon', title: 'Meer lucht – letterlijk', content: 'Na ongeveer 24 uur stopt je lichaam met het binnenkrijgen van koolmonoxide en begint een grote schoonmaak in je longen. Je kunt tijdelijk meer slijm ophoesten: dat is juist een goed teken.' },
      { icon: 'MoneyIcon', title: 'Meer geld', content: 'Rook je 1 pakje per dag van €8, dan bespaar je: ± €240 p/m, ± €1.440 in een half jaar, ± €2.880 in een jaar. Reken uit wat jij bespaart!' },
      { icon: 'TimeIcon', title: 'Meer tijd', content: 'Roken kost ongemerkt veel tijd. Stop je, dan heb je ineens extra tijd voor dingen die je wél belangrijk of leuk vindt.' },
      { icon: 'SleepIcon', title: 'Betere slaap', content: 'Nicotine is een stimulerend middel dat je slaap verstoort. Na de ontwenning slapen ex-rokers gemiddeld beter dan rokers.' },
      { icon: 'FocusIcon', title: 'Minder afleiding', content: 'Als roker ben je vaak bezig met de volgende sigaret. Na een paar weken stoppen merk je dat je langer geconcentreerd kunt zijn.' },
      { icon: 'DecisionIcon', title: 'Betere keuzes maken', content: 'Als je merkt dat je zélf kunt stoppen, voel je meer regie. Dat maakt het makkelijker om ook in andere dingen gezonder te kiezen.' },
      { icon: 'HealthIcon', title: 'Betere lichamelijke gezondheid', content: 'Na 1 jaar is het risico op hart- en vaatziekten gehalveerd. Na 10 jaar is de kans op longkanker gehalveerd. Een niet-roker leeft gemiddeld 10 jaar langer.' },
      { icon: 'ImmuneSystemIcon', title: 'Betere weerstand', content: 'Roken verzwakt het immuunsysteem. Stoppen verbetert de doorbloeding en vermindert ontstekingen; je afweer krijgt meer ruimte.' },
      { icon: 'MoodIcon', title: 'Betere stemming', content: 'Veel mensen denken dat roken helpt tegen stress, maar het neemt stress juist toe. Na het stoppen nemen angst-, stress- en depressieve klachten vaak af.' },
    ],
    readMore: "Vind meer feiten en cijfers over roken en stoppen bij betrouwbare bronnen zoals het Trimbos-instituut en het RIVM.",
    assignment: 'Schrijf in je dagboek in de app: “Waarom wil ik stoppen / minderen?” Maak een lijstje van minstens 5 voordelen die voor jou persoonlijk het belangrijkst zijn. Maak vandaag voor elke sigaret een foto in de app en noteer: waar was ik? met wie? hoe voelde ik me?',
    quiz: [],
  },
};
