import React from 'react';
import { 
    BrainCircuitIcon, ClockIcon, DumbbellIcon, FireIcon, HeartIcon, LeafIcon, PencilIcon,
    PlusIcon, SpeakerIcon, StarIcon, UsersIcon, UtensilsIcon, XCircleIcon, BedIcon, AwardIcon, ClipboardListIcon
} from '../../components/Icons';

export const sleepChallengeIconMap: Record<string, React.ComponentType<{ className?: string }>> = {
    EnergyIcon: FireIcon,
    FocusIcon: BrainCircuitIcon,
    DecisionIcon: PencilIcon,
    MemoryIcon: BrainCircuitIcon,
    StressIcon: LeafIcon,
    HealthIcon: HeartIcon,
    ImmuneSystemIcon: FireIcon,
    MoodIcon: HeartIcon,
    RoutineIcon: ClockIcon,
    BedIcon: BedIcon,
    SleepMaskIcon: XCircleIcon,
    ClearMindIcon: BrainCircuitIcon,
    ExerciseIcon: DumbbellIcon,
    NoPhoneIcon: XCircleIcon,
    NoCoffeeIcon: XCircleIcon,
    SunIcon: StarIcon,
    RelaxIcon: LeafIcon,
    UtensilsIcon: UtensilsIcon,
    SleepCycleIcon: ClockIcon,
    HeartIcon: HeartIcon,
    BloodPressureIcon: HeartIcon,
    WeightIcon: DumbbellIcon,
    VirusIcon: XCircleIcon,
    CancerIcon: XCircleIcon,
    SkullIcon: XCircleIcon,
    TiredFaceIcon: XCircleIcon,
    LifeDifficultyIcon: XCircleIcon,
    SelfEsteemIcon: AwardIcon,
    InsomniaIcon: BedIcon,
    ApneaIcon: XCircleIcon,
    RestlessLegsIcon: DumbbellIcon,
    DreamIcon: BrainCircuitIcon,
    NarcolepsyIcon: BedIcon,
    SleepwalkingIcon: BedIcon,
    SoundIcon: SpeakerIcon,
    SmellIcon: LeafIcon,
    BrainIcon: BrainCircuitIcon,
    TrafficIcon: XCircleIcon,
    AlcoholIcon: XCircleIcon,
    EyeIcon: XCircleIcon,
    HormoneIcon: FireIcon,
    PillsIcon: PlusIcon,
    DrugsIcon: XCircleIcon,
    PainkillerIcon: PlusIcon,
    CoffeeIcon: XCircleIcon,
    WorkIcon: ClipboardListIcon,
    PainIcon: HeartIcon,
    LungsIcon: HeartIcon,
    FamilyIcon: UsersIcon,
    MoneyIcon: FireIcon,
    BathIcon: LeafIcon,
    MusicIcon: SpeakerIcon,
    TeaIcon: UtensilsIcon,
    MeditateIcon: LeafIcon,
    TrophyIcon: AwardIcon,
};