
import React from 'react';
import { 
    BrainCircuitIcon, ClockIcon, DumbbellIcon, FireIcon, HeartIcon, LeafIcon, PencilIcon,
    PlusIcon, SpeakerIcon, StarIcon, UsersIcon, UtensilsIcon, XCircleIcon, BedIcon, AwardIcon, ClipboardListIcon,
    HomeIcon, ScaleIcon, WindIcon, TreesIcon, BeakerIcon, SmokingIcon, LungsIcon, DropletIcon, ShieldExclamationIcon,
    FaceFrownIcon, UserGroupIcon
} from '../../components/Icons';

export const stopRokenChallengeIconMap: Record<string, React.ComponentType<{ className?: string }>> = {
    EnergyIcon: FireIcon,
    LungsIcon: LungsIcon,
    MoneyIcon: StarIcon, // Using Star as a proxy for value/money
    TimeIcon: ClockIcon,
    SleepIcon: BedIcon,
    FocusIcon: BrainCircuitIcon,
    DecisionIcon: PencilIcon,
    HealthIcon: HeartIcon,
    ImmuneSystemIcon: ShieldExclamationIcon,
    MoodIcon: FaceFrownIcon,
    CancerIcon: XCircleIcon,
    HeartVesselsIcon: HeartIcon,
    AppearanceIcon: HomeIcon, // Placeholder
    AddictionIcon: BrainCircuitIcon,
    SecondHandSmokeIcon: UsersIcon,
    LongTermImpactIcon: ClockIcon,
    VirusesIcon: XCircleIcon,
    MentalHealthIcon: BrainCircuitIcon,
    NicotineTrapIcon: XCircleIcon,
    // FIX: Replace an undefined `MoodIcon` with `FaceFrownIcon` to resolve an import error.
    QuittingAndMoodIcon: FaceFrownIcon,
    ConditionIcon: DumbbellIcon,
    SkinHairTeethIcon: HomeIcon,
    StomachIntestinesIcon: UtensilsIcon,
    SexualityFertilityIcon: HeartIcon,
    PregnancyBabyIcon: UserGroupIcon,
    WeightIcon: ScaleIcon,
    HealthyEatingIcon: UtensilsIcon,
    HandHabitIcon: PencilIcon,
    MovementIcon: DumbbellIcon,
    SocietalImpactIcon: UserGroupIcon,
    YouthIcon: UsersIcon,
    CostsIcon: XCircleIcon,
    TobaccoIndustryIcon: XCircleIcon,
    StatementIcon: AwardIcon,
    AttemptsIcon: ClipboardListIcon,
    ReduceVsQuitIcon: ClipboardListIcon,
    LearningIcon: BrainCircuitIcon,
    StopPlanIcon: PencilIcon,
    AddictionNotFailureIcon: BrainCircuitIcon,
    ProfessionalHelpIcon: UsersIcon,
    MedicationIcon: PlusIcon,
    NeverTooLateIcon: ClockIcon,
    ThirdHandSmokeIcon: HomeIcon,
    RelationshipsIcon: UsersIcon,
    BoundariesIcon: ShieldExclamationIcon,
    DirectCostsIcon: StarIcon,
    IndirectCostsIcon: HeartIcon,
    WorkIncomeIcon: ClipboardListIcon,
    EmotionalCostsIcon: FaceFrownIcon,
    AppsIcon: StarIcon,
    OnlineHelpIcon: UsersIcon,
    CoachingBuddyIcon: UsersIcon,
    EmergencyPlanIcon: ShieldExclamationIcon,
    TriggersIcon: ClipboardListIcon,
    FourDMethodIcon: BrainCircuitIcon,
    BoredomIcon: ClockIcon,
    StressIcon: LeafIcon,
    InternalExternalMotivationIcon: FireIcon,
    YourWhyIcon: PencilIcon,
    RewardPlanIcon: AwardIcon,
    VisualizeFutureIcon: StarIcon,
    RelapseIcon: XCircleIcon,
    RelapsePlanIcon: PencilIcon,
    NewIdentityIcon: AwardIcon,
    KeepUsingToolsIcon: ClipboardListIcon,
    LookBackIcon: ClockIcon,
};